#!/usr/bin/env python
"""Command line interface to apply a warp transformation over a
   streamlines file"""
import argparse

from multiatlas.cli import segmentation_diffusion_inner as sd


if __name__ == "__main__":
    # Parser
    parser = argparse.ArgumentParser(description=("Creates a segmentation"
                                                  " based on the voting of"
                                                  " many experts"))

    parser.add_argument('-atlases', dest='atlases', required=True, type=str,
                        nargs='+', help='atlases of the train subjects')

    parser.add_argument('-tracts', dest='tracts', required=True, type=str,
                        nargs='+', help='tracts of the train subjects')

    parser.add_argument('-dwi', dest='dwi', required=True, type=str,
                        help='Diffusion image of test subject')

    parser.add_argument('-bvals', dest='bvals', required=True, type=str,
                        help='bvals file')

    parser.add_argument('-bvecs', dest='bvecs', required=True, type=str,
                        help='bvecs file')

    parser.add_argument('-out', dest='outfile', required=True, type=str,
                        help="outfile")

    args = parser.parse_args()

    sd.segmentation(args.atlases, args.tracts, args.dwi,
                    args.bvals, args.bvecs, args.outfile)
