#!/usr/bin/env python
"""Command line interface to apply a warp transformation over a
   streamlines file"""
import argparse

from multiatlas.cli import segmentation_voting as sv


if __name__ == "__main__":
    # Parser
    parser = argparse.ArgumentParser(description=("Creates a segmentation"
                                                  " based on the voting of"
                                                  " many experts"))

    parser.add_argument('-atlases', dest='atlases', required=True, type=str,
                        nargs='+', help='atlases to join by voting')

    parser.add_argument('-out', dest='outfile', required=True, type=str,
                        help="outfile")

    args = parser.parse_args()

    sv.segmentation_voting(args.atlases, args.outfile)
