#!/usr/bin/env python
"""Command line interface to apply a warp transformation over a
   streamlines file"""
import argparse

from multiatlas.cli import segmentation_voting_tracts as svt


if __name__ == "__main__":
    # Parser
    parser = argparse.ArgumentParser(description=("Creates a segmentation"
                                                  " based on the voting of"
                                                  " many experts"))

    parser.add_argument('-tracts', dest='tracts', required=True, type=str,
                        nargs='+', help='tracts of the train subjects')

    parser.add_argument('-dwi', dest='dwi', required=True, type=str,
                        help='Diffusion image of test subject')

    parser.add_argument('-out', dest='outfile', required=True, type=str,
                        help="outfile")

    args = parser.parse_args()

    svt.segmentation(args.tracts, args.dwi, args.outfile)
