#!/usr/bin/env python
"""Command line interface to apply a warp transformation over a
   streamlines file"""
import argparse

from multiatlas.cli import segmentation_rohlfing as sr


if __name__ == "__main__":
    # Parser
    parser = argparse.ArgumentParser(description=("Creates a segmentation"
                                                  " based on the method of"
                                                  " rofhling (2004)"))

    parser.add_argument('-atlases', dest='atlases', required=True, type=str,
                        nargs='+', help='atlases to join')

    parser.add_argument('-out', dest='outfile', required=True, type=str,
                        help="name of the output segmentation")

    parser.add_argument('-cout', dest='coutfile', type=str,
                        help="name of the output confusion matrix")

    args = parser.parse_args()

    sr.segmentation_rohlfing(args.atlases, args.outfile, args.coutfile)
